export enum AlignmentBaseline {
  AFTER_EDGE = 'after-edge',
  ALPHABETIC = 'alphabetic',
  AUTO = 'auto',
  BASELINE = 'baseline',
  BEFORE_EDGE = 'before-edge',
  BOTTOM = 'bottom',
  CENTER = 'center',
  CENTRAL = 'central',
  HANGING = 'hanging',
  IDEOGRAPHIC = 'ideographic',
  MATHEMATICAL = 'mathematical',
  MIDDLE = 'middle',
  TEXT_AFTER_EDGE = 'text-after-edge',
  TEXT_BEFORE_EDGE = 'text-before-edge',
  TOP = 'top',
}